[package]
name = "pinpad"
version = "0.1.0"
edition = "2021"
authors = ["Hiroshi"]
description = "Biblioteca para comunicação com Pinpad via Protocolo ABECS 2.12"
license = "MIT"

[lib]
name = "pinpad"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
serialport = "4.8.1"
qrcode = "0.14.1"
image = { version = "0.25.10", default-features = false, features = ["png"]  }
jni = "0.21.1"